services:

  flask:
    build: ./backend
    container_name: smartlink-flask

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: smartlink-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: